VIDEO_PATH = "test.mp4"
ZONES_FILE = "restricted_zones.json"

YOLO_MODEL = "yolov8x.pt"
YOLO_CONFIDENCE = 0.2
YOLO_DEVICE = "mps"
YOLO_IMGSZ = 640

USE_DEEPSORT = False
TRACK_EVERY_N_FRAMES = 1
DEEPSORT_RESIZE_FACTOR = 0.8
DEEPSORT_MAX_AGE = 15
DEEPSORT_N_INIT = 20
TRACK_IOU_THRESHOLD = 0.2
TRACK_CENTER_DISTANCE_THRESHOLD = 30
MIN_TRACK_DISTANCE = 80

PROCESS_EVERY_N_FRAMES = 2
RESIZE_FACTOR = 1.0

ALARM_DELAY_SECONDS = 3.0

ZONE_COLOR = (0, 255, 0)
ZONE_THICKNESS = 2
DETECTION_COLOR = (255, 0, 0)
DETECTION_THICKNESS = 3
ALARM_COLOR = (0, 0, 255)
ALARM_FONT_SCALE = 2.0
ALARM_FONT_THICKNESS = 3

SHOW_FPS = True
FPS_POSITION = (10, 30)
FPS_UPDATE_INTERVAL = 10

MIN_DETECTION_AREA_RATIO = 0.0001
MIN_DETECTION_HEIGHT_RATIO = 0.01
MAX_ASPECT_RATIO = 1.0
MIN_ASPECT_RATIO = 0.3
MIN_CONFIDENCE_AFTER_FILTER = 0.25
IOU_THRESHOLD = 0.4
YOLO_IOU_THRESHOLD = 0.35
YOLO_MAX_DETECTIONS = 200

MAX_TRACK_DISTANCE = 150
MIN_ZONE_POINTS = 3

MIN_TRACK_AGE_FOR_INTRUSION = 5
MIN_INTRUSION_FRAMES = 3
INTRUSION_CONFIRMATION_RATIO = 0.7

WINDOW_NAME = "Intrusion Detection System"
ZONE_MARKER_WINDOW_NAME = "Zone Marker - Press 's' to save, 'r' to reset, 'q' to quit"

SHOW_TRAJECTORIES = False
SHOW_ZONE_FILL = False
TRAJECTORY_LENGTH = 50
ZONE_FILL_ALPHA = 0.2

KEY_QUIT = ord('q')

